"""Frozen v1 schema and append-only audit guards."""

from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actors",
        sa.Column("type", sa.String(length=24), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("relationship", sa.String(length=120), nullable=False),
        sa.Column("country", sa.String(length=3), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "audit_events",
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=False),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_hash"),
        sa.UniqueConstraint("sequence"),
    )
    op.create_table(
        "transfer_routes",
        sa.Column("provider_name", sa.String(length=160), nullable=False),
        sa.Column("from_currency", sa.String(length=3), nullable=False),
        sa.Column("to_currency", sa.String(length=3), nullable=False),
        sa.Column("fixed_fee", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("percentage_fee", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("fx_rate", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("fx_markup", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("min_transfer", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("max_transfer", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("settlement_p50_days", sa.Integer(), nullable=False),
        sa.Column("settlement_p95_days", sa.Integer(), nullable=False),
        sa.Column("availability", sa.String(length=20), nullable=False),
        sa.Column("verification_status", sa.String(length=30), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("fixed_fee >= 0 AND percentage_fee >= 0 AND percentage_fee < 1"),
        sa.CheckConstraint("fx_markup >= 0 AND fx_markup < 1"),
        sa.CheckConstraint("fx_rate > 0"),
        sa.CheckConstraint("min_transfer >= 0 AND max_transfer >= min_transfer"),
        sa.CheckConstraint("settlement_p95_days >= settlement_p50_days AND settlement_p50_days >= 0"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "documents",
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=240), nullable=False),
        sa.Column("document_type", sa.String(length=40), nullable=False),
        sa.Column("trust_level", sa.String(length=2), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("security_flags", sa.JSON(), nullable=False),
        sa.Column("target_obligation_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["actors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "permissions",
        sa.Column("owner_actor_id", sa.String(length=36), nullable=False),
        sa.Column("target_actor_id", sa.String(length=36), nullable=False),
        sa.Column("resource_type", sa.String(length=40), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("permission_type", sa.String(length=40), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_actor_id"],
            ["actors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_actor_id"],
            ["actors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plans",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("objective_value", sa.Float(), nullable=False),
        sa.Column("total_estimated_cost", sa.Float(), nullable=False),
        sa.Column("stress_failure_rate", sa.Float(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["actors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document_blocks",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("block_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "intervention_candidates",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=80), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["actors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "obligations",
        sa.Column("owner_actor_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("beneficiary", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("partial_payment_allowed", sa.Boolean(), nullable=False),
        sa.Column("minimum_payment", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("verification_status", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("beneficiary_verified", sa.Boolean(), nullable=False),
        sa.Column("security_hold", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("source_document_id", sa.String(length=36), nullable=True),
        sa.Column("installment_option", sa.JSON(), nullable=True),
        sa.Column("confirmation_note", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0"),
        sa.CheckConstraint("minimum_payment >= 0 AND minimum_payment <= amount"),
        sa.ForeignKeyConstraint(
            ["owner_actor_id"],
            ["actors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scenario_runs",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("iterations", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["actors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "financial_facts",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("field", sa.String(length=40), nullable=False),
        sa.Column("raw_value", sa.Text(), nullable=False),
        sa.Column("normalized_value", sa.Text(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("date_value", sa.Date(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("verification_status", sa.String(length=30), nullable=False),
        sa.Column("source_page", sa.Integer(), nullable=False),
        sa.Column("source_block", sa.String(length=36), nullable=False),
        sa.Column("evidence_text", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_block"],
            ["document_blocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scenario_results",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["scenario_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "funding_sources",
        sa.Column("owner_actor_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("available_from", sa.Date(), nullable=False),
        sa.Column("availability_status", sa.String(length=30), nullable=False),
        sa.Column("verification_status", sa.String(length=30), nullable=False),
        sa.Column("restriction_type", sa.String(length=30), nullable=False),
        sa.Column("minimum_remaining_balance", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_fact_id", sa.String(length=36), nullable=True),
        sa.Column("confirmation_note", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount >= 0"),
        sa.CheckConstraint("minimum_remaining_balance >= 0 AND minimum_remaining_balance <= amount"),
        sa.ForeignKeyConstraint(
            ["owner_actor_id"],
            ["actors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_fact_id"],
            ["financial_facts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["actors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plan_allocations",
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("funding_source_id", sa.String(length=36), nullable=False),
        sa.Column("obligation_id", sa.String(length=36), nullable=False),
        sa.Column("transfer_route_id", sa.String(length=36), nullable=False),
        sa.Column("source_amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("destination_amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("expected_arrival_date", sa.Date(), nullable=False),
        sa.Column("estimated_fee", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["funding_source_id"],
            ["funding_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["obligations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transfer_route_id"],
            ["transfer_routes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prepared_actions",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("requested_by", sa.String(length=36), nullable=False),
        sa.Column("approved_by", sa.String(length=36), nullable=True),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("level", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("obligation_id", sa.String(length=36), nullable=True),
        sa.Column("funding_source_id", sa.String(length=36), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["actors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["funding_source_id"],
            ["funding_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["obligations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["actors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["actors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute(
            "CREATE FUNCTION lattice_audit_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'audit history is append only'; END; $$"
        )
        op.execute(
            "CREATE TRIGGER audit_immutable BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION lattice_audit_immutable()"
        )
    elif bind.dialect.name == "sqlite":
        op.execute(
            "CREATE TRIGGER audit_no_update BEFORE UPDATE ON audit_events BEGIN SELECT RAISE(ABORT, 'audit history is append only'); END"
        )
        op.execute(
            "CREATE TRIGGER audit_no_delete BEFORE DELETE ON audit_events BEGIN SELECT RAISE(ABORT, 'audit history is append only'); END"
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prepared_actions")
    op.drop_table("plan_allocations")
    op.drop_table("funding_sources")
    op.drop_table("scenario_results")
    op.drop_table("financial_facts")
    op.drop_table("scenario_runs")
    op.drop_table("obligations")
    op.drop_table("intervention_candidates")
    op.drop_table("document_blocks")
    op.drop_table("plans")
    op.drop_table("permissions")
    op.drop_table("documents")
    op.drop_table("auth_sessions")
    op.drop_table("transfer_routes")
    op.drop_table("audit_events")
    op.drop_table("actors")
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP FUNCTION IF EXISTS lattice_audit_immutable()")
